name: Fluxus CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x] # Test against common LTS versions

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm' # Enable caching for npm dependencies
        cache-dependency-path: fluxus/package-lock.json # Specify lock file path relative to root

    - name: Install dependencies
      working-directory: ./fluxus # Specify working directory for npm commands
      run: npm ci # Use ci for faster, deterministic installs

    - name: Run type checking
      working-directory: ./fluxus
      run: npm run typecheck

    - name: Run tests
      working-directory: ./fluxus
      run: npm run test

    # Optional: Add a build step if needed
    # - name: Build project
    #   working-directory: ./fluxus
    #   run: npm run build